swagger: "2.0"
info:
  version: 0.0.5
  title: Payments Service APIs
  description: API for Payments Backend Service
# during dev, should point to your local machine
# basePath prefixes all resource paths 
basePath: /payment-service
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
- name: Payments
  description: All Payments Endpoints
paths:
  #--------------------------------------------------------Payments----------------------------------------------#
  /payments/authorizenet:
    # binds a127 app logic to a route
    x-swagger-router-controller: authorizeNetController
    post:
      tags:
        - Payments
      description: Make payments from authorize.net provider
      # used as the method name of the controller
      operationId: makePaymentFromAcceptMethod
      parameters: 
        - $ref: '#/parameters/Authorization'
        - name: data
          in: body
          description: request body for accept method
          required: true
          schema:
            $ref: '#/definitions/AcceptMethodRequestBody'
      responses:
        "200":
          description: Success
        # responses may fall through to errors
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /payments/stemcells/authorizenet:
    # binds a127 app logic to a route
    x-swagger-router-controller: authorizeNetController
    post:
      tags:
        - Payments
      description: Make payments from authorize.net provider
      # used as the method name of the controller
      operationId: makePaymentFromAcceptMethodWithoutCompanyId
      parameters: 
        - name: data
          in: body
          description: request body for accept method
          required: true
          schema:
            $ref: '#/definitions/AcceptMethodRequestBody'
      responses:
        "200":
          description: Success
        # responses may fall through to errors
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /payments/search:
    # binds a127 app logic to a route
    x-swagger-router-controller: index
    post:
      tags:
        - Payments
      description: Get Payments from transactionId
      # used as the method name of the controller
      operationId: getPayments
      parameters: 
        - name: data
          in: body
          description: request body for get Payments
          required: true
          schema:
            $ref: '#/definitions/GetPaymentRequest'
      responses:
        "200":
          description: Success
        # responses may fall through to errors
          schema:
            type : array
            # a pointer to a definition
            $ref: "#/definitions/PaymentResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  

  /swagger:
    x-swagger-pipe: swagger_raw
    
# complex objects have schema definitions

  #----------------------------------------- Parameters ----------------------------------------------#

parameters: 
  Authorization:
    in: header
    name: Authorization
    type: string
    required: true

  #--------------------------------------- Defintions -------------------------------------#

definitions:

  #--------------------------------------------------Payments --------------------------------------#
  Address:
    properties:
      address: 
        type: "string"
        example: "529 Mansarovar Plaza1212"
      city: 
        type: "string"
        example: "Jaipur"
      country: 
        type: "string"
        example: "India"
      state: 
        type: "string"
        example: "Rajasthan"
      zipCode: 
        type: "string"
        example: "3232"
      addressType: 
        type: "boolean"
        example: false
  AcceptMethodRequestBody:
    properties: 
      amount:
        type: number
        example: 23.99
      currency:
        type: string
        example: USD
      paymentTerms:
        type: string
        example: 'current'
      paymentMethod:
        type: string
        example: 'CC'
      billingAddress:
        $ref: '#/definitions/Address'
      shippingAddress:
        $ref: '#/definitions/Address'
      paymentReceiver:
        properties:
          id: 
            type: string
            example: '0XIO12903'
          name: 
            type: string
            example: 'John Doe'
      payer:
        properties:
          id: 
            type: string
            example: '909320'
          name:
            type: string
            example: 'Jane Doe'
      opaqueData:
        properties: 
          dataDescriptor: 
            type: "string"
            example: "COMMON.ACCEPT.INAPP.PAYMENT"
          dataValue: 
            type: "string"
            example: "eyJjb2RlIjoiNTBfMl8wNjAwMDUzNUE1OTkzREQ1NEM1NzY0OTgwNTZDQzY5MEVBRjY5MTU3RjBEQThEMjU2N0EyQkUwMUNBNzQ5QkY0ODRDMTgyMjRGN0IzMEE4REI2MUJDQUI1NDMxMTZCNzkwOUM3OUMwIiwidG9rZW4iOiI5NTA3OTE3MzE1NTg5OTYzOTA0NjA0IiwidiI6IjEuMSJ9"
        type: "object"
      messages: 
        required: 
          - "resultCode"
          - "message"
        properties: 
          statusCode: 
            type: "string"
            example: "I_WC_O1"
          encryptedCardData:
            properties: 
              cardNumber: 
                type: "string"
                example: "XXXXXXXXXXXX1111"
              expDate: 
                type: "string"
                example: "12/22"
              bin: 
                type: "string"
                example: "411111"
  PaymentResponse: 
    properties: 
      _id: 
        type: "string"
        example: "5bb467fac1eb164d3dafb973"
      receivedBy: 
        properties: 
          id: 
            type: "string"
            example: "test"
          name: 
            type: "string"
            example: "test_name"
      payer: 
        properties: 
          id: 
            type: "string"
            example: "payer"
          name: 
            type: "string"
            example: "payer name"
      paymentTerms: 
        type: "string"
        example: "NET45"
      paymentMethod: 
        type: "string"
        example: "CASH"
      paymentStatus: 
        type: "string"
        example: "FAILED"
      vendor: 
        type: "string"
        example: "Authorize.net"
      createdOn: 
        type: "string"
        example: "2018-10-03T06:55:54.169+0000"
      transactionId: 
        type: "string"
        example: "50sdif99jmssss3d"
      amountPaid: 
        type: "number"
        example: 1
      currency: 
        type: "string"
        example: "USD"
      modifiedOn: 
        type: "string"
        example: "2018-10-03T06:55:54.170+0000"
      vendorResponse: 
        type: object
  GetPaymentRequest: 
    properties: 
      transactionIds: 
        type: "array"
        items: 
          type: "string"
        example: 
          - "2sc99hchi2jmakvayr"



  SuccessResponse:
    type: object
    properties:
      status:
        type: string
        example: 'PAYMENT_SUCCESS'
      paymentId:
        type: string
        example: 'xy138032_pay'
    
  ErrorResponse:
    type: object