url:
    path:
        accountsPayableService: http://accounts-payable-service
        inventoryService: http://inventory-management-service
        mediaService: https://media-service
        notificationService: http://notification-service
        
envs:
  authorizenetEnv: 'sandbox'
  
http:
    requestTimeOutInMs: 20000


dbConfigs:
  protocol: mongodb
  host: hosturl
  port: hostport



messageBroker:
    connectionTimeout: 10000
    host: url
    port: 5672
    login: 'abc'
    password: 'abc'
    
date:
  format : "MMMM Do YYYY"
  timeZone: "Asia/Kolkata"

passOnRequestHeaders: "Authorization,CorrelationId,Content-Type"
